g_shop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

g_shop/cartapp/urls.py
from django.urls import path

import cartapp.views as cartapp

app_name = 'basketapp'

urlpatterns = [
    path('', cartapp.cart, name='view'),
    path('add/<int:pk>/', cartapp.cart_add, name='add'),
    path('remove/<int:pk>)/', cartapp.cart_remove, name='remove'),
]

g_shop/g_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp.views import main, product, contact, about

# from mainapp.views import ProductDetailView


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),

    path('', include('mainapp.urls', namespace='main')),  #

    # path('', main, name='index'),
    # path('products/', product, name='products'),
    # path('products/', include('mainapp.urls', namespace='products')),
    # path('contact/', contact, name='contact'),
    # path('about/', about, name='about'),

    # path('products_all', product, name='products_all'),
    # path('products_recommendation', product, name='products_recommendation'),
    # path('products_action', product, name='products_action'),
    # path('products_sale', product, name='products_sale'),

    path('auth/', include('authapp.urls', namespace='auth')),
    path('cart/', include('cartapp.urls', namespace='cart')),

    # path('products/<str:ct_models>/<str:slug>/', ProductDetailView.as_view(), name='product_detail')  # Для отображения по другому
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

g_shop/mainapp/urls.py
from django.urls import path

# from .views import ProductDetailView
from .views import *

# import mainapp.views as mainapp


app_name = 'mainapp'

urlpatterns = [

    path('', main, name='index'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('products/', product, name='products'),

    path('products_all', product, name='products_all'),
    path('products_recommendation', product, name='products_recommendation'),
    path('products_action', product, name='products_action'),
    path('products_sale', product, name='products_sale'),

    # path('products/<str:ct_models>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),  # другая модель вывода данных
    # path('', mainapp.product, name='index'),
    # path('category/<int:pk>/', product, name='category'),

    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),

]

g_shop/mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse


User = get_user_model()


# def get_product_url(obj, viwename):
#     ct_model = obj.__class__._meta.model_name
#     return reverse(viwename, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class Category(models.Model):
    name = models.CharField(primary_key=True, max_length=150, verbose_name='Категория', unique=True)
    descriptions = models.TextField(verbose_name='Описание', blank=True)
    slug = models.SlugField(unique=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=150, verbose_name='Наименование')
    image = models.ImageField(upload_to='product_images', blank=True)
    short_desc = models.CharField(max_length=150, verbose_name='Краткое описание', blank=True)
    description = models.TextField(verbose_name='Полное описание', blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена', default=0)
    quantity = models.PositiveIntegerField(verbose_name='Количество на складе', default=0)

    def __str__(self):
        return f'{self.name} ({self.category.name})'


class Shoes(Product):
    brand_name = models.CharField(max_length=150, verbose_name='Бренд')
    size = models.CharField(max_length=2, verbose_name='Размер')
    gender = models.CharField(max_length=1, verbose_name='Пол')
    color = models.CharField(max_length=50, verbose_name='Цвет')

    def __str__(self):
        return f'{self.name}, {self.brand_name}, {self.size}'

    # def get_absolute_url(self):
    #     return get_product_url(self, 'product_detail')


class Clothes(Product):
    brand_name = models.CharField(max_length=150, verbose_name='Бренд')
    size = models.CharField(max_length=2, verbose_name='Размер')
    gender = models.CharField(max_length=1, verbose_name='Пол')
    color = models.CharField(max_length=50, verbose_name='Цвет')

    def __str__(self):
        return f'{self.name}, {self.brand_name}, {self.size}'

    # def get_absolute_url(self):
    #     return get_product_url(self, 'product_detail')


class Toy(Product):
    brand_name = models.CharField(max_length=150, verbose_name='Бренд')
    t_type = models.CharField(max_length=150, verbose_name='Тип игрушки')
    color = models.CharField(max_length=50, verbose_name='Цвет')

    def __str__(self):
        return f'{self.t_type}, {self.brand_name}, {self.name}'

    # def get_absolute_url(self):
    #     return get_product_url(self, 'product_detail')


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    quantity = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Стоимость', default=0)

    def __str__(self):
        return f'Продукт {self.product.name}, количество: {self.quantity}, общая стоимость: {self.final_price}'


class Cart(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Владелец корзины', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Стоимость', default=0)

    def __str__(self):
        return f'Корзина: {self.owner}, id: {self.id}, Цена всего: {self.final_price}'


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    def __str__(self):
        return f'Покупатель: {self.user.first_name} {self.user.last_name}'

g_shop/mainapp/views.py
from json import load

from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView

from cartapp.models import Cart
from .models import Shoes, Clothes, Toy, Category

# Create your views here.
from mainapp.models import Shoes, Clothes, Toy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def read(content):
    with open(f"mainapp/templates/json/{content}.json", "r", encoding='UTF-8') as read_file:
        return load(read_file)


links_menu = read('links_menu')
header_menu = read('header_menu')


# links_menu = [
#     {'href': 'main:products_all', 'name': 'Все товары'},
#     {'href': 'main:products_recommendation', 'name': 'Рекомендуем'},
#     {'href': 'main:products_action', 'name': 'Акции'},
#     {'href': 'main:products_sale', 'name': 'Распродажа'},
# ]

# header_menu = [
#     {'href': 'main:index', 'name': 'ДОМОЙ'},
#     {'href': 'main:products', 'name': 'НАШИ ТОВАРЫ'},
#     {'href': 'main:about', 'name': 'О НАС'},
#     {'href': 'main:contact', 'name': 'НАШИ КОНТАКТЫ'},
# ]


def main(request, pk=None):  # , pk=None

    shoes = Shoes.objects.all()
    clothes = Clothes.objects.all()
    toys = Toy.objects.all()
    products = shoes.union(clothes)

    content = {
        'title': 'Главная',
        'header_menu': header_menu,
        'shoes': shoes,
        'clothes': clothes,
        'toys': toys,
        'products': products

    }
    return render(request, 'mainapp/index.html', content)


def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = Category.objects.filter(is_active=True)
    cart = Cart.objects.filter(user=request.user)

    links_menu_category = Category.objects.all()

    links_menu_shoes = Shoes.objects.all()
    links_menu_clothes = Clothes.objects.all()
    links_menu_toys = Toy.objects.all()
    links_menu_product = links_menu_shoes.union(links_menu_clothes)

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = links_menu_product.objects.filter(is_active=True,
                                                         category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(Category, pk=pk)
            products = links_menu_product.objects.filter(category__pk=pk,
                                                         is_active=True, category__is_active=True).order_by('price')

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'cart': cart,
        }

        return render(request, 'mainapp/products_list.html', content)


def product(request, pk=None):  # , pk=None

    links_menu_category = Category.objects.all()

    links_menu_shoes = Shoes.objects.all()
    links_menu_clothes = Clothes.objects.all()
    links_menu_toys = Toy.objects.all()
    links_menu_product = links_menu_shoes.union(links_menu_clothes)  # , links_menu_toys
    # links_menu_product = Shoes.objects.raw('SELECT * FROM Shoes UNION SELECT * FROM Clothes UNION SELECT * FROM Toy')

    if pk is not None:

        cart = []
        if request.user.is_authenticated:
            cart = Cart.objects.filter(user=request.user)

        if pk == 0:
            products = links_menu_product.order_by('price')  #
            category = {'name': 'Все'}
        else:
            category = get_object_or_404(links_menu_category, pk=pk)
            products = links_menu_product.filter(category__pk=pk).order_by('price')  #

        content = {
            'title': 'Товары',
            'links_menu': links_menu,
            'links_menu_product': links_menu_category,
            'header_menu': header_menu,
            'category': category,
            'products': products,
            'cart': cart
        }

        return render(request, 'mainapp/products_list.html', content)

    same_products = links_menu_product  # [3:5]

    content = {
        'title': 'Товары',
        'links_menu': links_menu,
        'header_menu': header_menu,
        'links_menu_product': links_menu_category,
        'same_products': same_products
    }

    return render(request, 'mainapp/products.html', content)


def contact(request):
    content = {
        'title': 'Контакты',
        'header_menu': header_menu,
    }
    return render(request, 'mainapp/contact.html', content)


def about(request):
    content = {
        'title': 'О нас',
        'header_menu': header_menu,
    }
    return render(request, 'mainapp/about.html', content)

# def context(request):
#     content = {
#         'title': 'Магазин',
#         'header': 'Добро пожаловать на сайт',
#         'username': 'Галкин Антон',
#         'products': [
#             {'name': 'Шапки'},
#         ]
#     }
#     return render(request, 'mainapp/about.html')

g_shop/mainapp/templates/includes/categories_menu.html
<ul>
    {% for link in links_menu_category %}
    <li href="{% url link.href %}"
        class="{% if request.resolver_match.url_name == link.href %}active{% endif %}"
        data-filter="{% if link.name == 'Все товары' %}*{% elif link.name == 'Рекомендуем' %}.des{% elif link.name == 'Акции' %}.dev{% elif link.name == 'Распродажа' %}.gra{% endif %}">
        {{ link.name }}
    </li>
    {% endfor %}
</ul>

g_shop/mainapp/templates/includes/header_menu.html
<ul class="navbar-nav ml-auto">
    {% for link in header_menu %}
    <li class="nav-item {% if request.resolver_match.url_name == link.href %}active{% endif %}">
        <a class="nav-link" href="{% url link.href %}">{{ link.name }}</a>
    </li>
    {% endfor %}

    {% if user.is_authenticated %}
    <li class="nav-item {% if request.resolver_match.url_name == link.href %}active{% endif %}">
        <a class="nav-link" href="{% url 'auth:edit' %}">{{ user.first_name|default:'Пользователь' }}</a>
    </li>
    {% endif %}

    <li class="nav-item {% if request.resolver_match.url_name == link.href %}active{% endif %}">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
          <a class="nav-link" href="{% url 'auth:login' %}">>Вход</a>
        {% endif %}
    </li>

    <li class="nav-item {% if request.resolver_match.url_name == link.href %}active{% endif %}">

          <a href="{% url 'cart:view' %}" class="nav-link" >
              <span>
                  {% if cart %} {{ cart|length }} {% endif %}
              </span>
          </a>
    </li>

</ul>

g_shop/mainapp/templates/includes/inc_categories_menu.html
<ul>
    {% for link in links_menu %}
    <li href="{% url link.href %}"
        class="{% if request.resolver_match.url_name == link.href %}active{% endif %}"
        data-filter="{% if link.name == 'Все товары' %}*{% elif link.name == 'Рекомендуем' %}.des{% elif link.name == 'Акции' %}.dev{% elif link.name == 'Распродажа' %}.gra{% endif %}">
        {{ link.name }}
    </li>
    {% endfor %}
</ul>

g_shop/mainapp/templates/includes/new_collection.html
{% for product in clothes %}
<div class="col-md-4">
    <div class="product-item">
        <a href="/media/{{ product.image }}"><img src="/media/{{ product.image }}" alt="Картинка" height=""></a>
        <div class="down-content">
            <a href="{% url 'cart:add' product.pk %}"><h4>{{ product.name }}</h4></a>
            <h6>{{ product.price }} &#8381;</h6>
            <p>{{ product.short_desc }}</p>
            <ul class="stars">
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
            </ul>
            <span>Обзоры (24)</span>
        </div>
    </div>
</div>
{% endfor %}

{% for product in shoes %}
<div class="col-md-4">

    <div class="product-item">
        <a href="/media/{{ product.image }}"><img src="/media/{{ product.image }}" alt="Картинка"></a>
        <div class="down-content">
            <a href="{% url 'cart:add' product.pk %}"><h4>{{ product.name }}</h4></a>
            <h6>{{ product.price }} &#8381;</h6>
            <p>{{ product.short_desc }}</p>
            <ul class="stars">
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
            </ul>
            <span>Обзоры (24)</span>
        </div>
    </div>
</div>
{% endfor %}

{% for product in toys %}
<div class="col-md-4">

    <div class="product-item">
        <a href="/media/{{ product.image }}"><img src="/media/{{ product.image }}" alt="Картинка"></a>
        <div class="down-content">
            <a href="{% url 'cart:add' product.pk %}"><h4>{{ product.name }}</h4></a>
            <h6>{{ product.price }} &#8381;</h6>
            <p>{{ product.short_desc }}</p>
            <ul class="stars">
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
            </ul>
            <span>Обзоры (24)</span>
        </div>
    </div>
</div>
{% endfor %}

g_shop/mainapp/templates/includes/product_content.html
{% for product in clothes %}
<div class="col-lg-4 col-md-4 all des">
    <div class="product-item">
        <a href="/media/{{ product.image }}"><img src="/media/{{ product.image }}" alt=""></a>
        <div class="down-content">
            <a href="#"><h4>{{ product.name }}</h4></a>
            <h6>{{ product.price }} &#8381;</h6>
            <p>{{ product.short_desc }}</p>
            <ul class="stars">
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
                <li><i class="fa fa-star"></i></li>
            </ul>
            <span>Просмотров (12)</span>
        </div>
    </div>
</div>
{% endfor %}